### ISSUE TITLE
docs: more clear and precise steps to get started using ios and android

### ISSUE THREAD

**Issue by edwardz8** [nuxt-modules/ionic#114]
### 📚 Is your documentation request related to a problem?

A set of instructions to get a Nuxt project to work with Ionic along with ios or android.

`
npx @ionic/cli integrations enable capacitor
npx cap add ios
npx cap add android

`

Following the above approach, while following along with the capacitor docs, it isn't clear on the capacitor or nuxt documention pages that represent step-by-step instructions on how to get a Ionic ios or android project running with Nuxt.

Here are the exact steps I followed to get a working project running:

`
ionic init

npx @ionic/cli integrations enable capacitor

npm i @capacitor/ios

npx cap add ios
`

In package.json within the script tag, add:

`
"ionic:build": "npm run generate"
`

Then you must build the project with: 

`
npm run build
`

Then a pages/index.vue file needs to be present which is mentioned in the Nuxt Ionic module docs.

i looked at this repo: https://github.com/danielroe/nuxt-ionic/tree/main/playground 

however, there's no working example with a ios or android folder. for ios, when running the following the below error is thrown:

`
npx cap open ios 
npx cap run ios 
`

![ios-error](https://user-images.githubusercontent.com/25441286/197014630-b79c6880-ac81-479b-a53c-9aec9fa6f1b0.png)

### 🔍 Where should you find it?

Nuxt 3 Module Instructions: https://ionic.nuxtjs.org/getting-started/ 

### ℹ️ Additional context

ionic ios docs: https://capacitorjs.com/docs/ios 

Also, when using the ionic vs code extension and try to build or sync the app these errors appear:

![build-sync-errors](https://user-images.githubusercontent.com/25441286/197015975-1eead7e1-4716-45f4-b433-a579dde163f3.png)

**Comment by ceceliacreates** [comment]
Getting a PR together for this
