### ISSUE TITLE
fix: Android app empty screen

### ISSUE THREAD

**Issue by fristyr** [nuxt-modules/ionic#143]
### 🐛 The bug

I was trying to start my project with `ionic cap run android -l --external`
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/33237937/201480772-d6402d5c-d073-4823-8ab5-c954d2753bff.png">

### 🛠️ To reproduce

https://stackblitz.com/edit/github-452wac

### 🌈 Expected behaviour

Instead of empty screen I was expected to see the same content as in web version

On IOS it's fine
<img width="383" alt="image" src="https://user-images.githubusercontent.com/33237937/201486020-305b3cac-eadd-4628-b2a3-b323e69ec4a6.png">

**Comment by fristyr** [comment]
After I updated my SDK and android studio and updated some emulators, the issue is gone

**Comment by danielroe** [comment]
Great!
