### ISSUE TITLE
fix: NuxtConfig -> Ionic -> Config -> navAnimation doesn't work

### ISSUE THREAD

**Issue by fristyr** [nuxt-modules/ionic#156]
### 🐛 The bug

So according to the [docs](https://ionicframework.com/docs/vue/config) I should be able to override all ionic navigation animations, but when I do that nothing happens and I still see the default animations. 
Seems like `navAnimation `doesn't work

<img width="402" alt="image" src="https://user-images.githubusercontent.com/33237937/202871320-1b4fed07-a25d-436f-8c86-4387bb8e80be.png">

### 🛠️ To reproduce

stackblitz.com/edit/github-452wac

### 🌈 Expected behaviour

I want to be able to override default ionic navigation animations

**Comment by danielroe** [comment]
@fristyr Were you able to resolve this?
