### ISSUE TITLE
fix: template/default.vue not rendering after module added

### ISSUE THREAD

**Issue by bonomite** [nuxt-modules/ionic#217]
### 🐛 The bug

When I install and include @nuxt/ionic in the modules in the nuxt.config, everything in the default.vue template is ignored/does not render.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-6z4cfw?file=package.json,nuxt.config.ts,pages%2Findex.vue,layouts%2Fdefault.vue

### 🌈 Expected behaviour

the default.vue template should behave as normal. In this case, it would show a TEMPLATE MOUNTED and the fake HEADER and FOOTER

**Comment by danielroe** [comment]
You can add an `app.vue` file with the following content:

```vue
<template>
  <ion-app>
    <NuxtLayout>
      <ion-router-outlet />
    </NuxtLayout>
  </ion-app>
</template>

<script setup>
import { IonApp, IonRouterOutlet } from '@ionic/vue'
</script>
```

**example**: https://stackblitz.com/edit/nuxt-starter-bmvvn1.

We should add this to the docs.

**Comment by bonomite** [comment]
Thanks @danielroe! Seems to work well. I just had to add `position:relative;` to the `,ion-router-outlet/>` to behave as expected.
