### ISSUE TITLE
help: Unable to figure out how to install Nuxt and Ionic together

### ISSUE THREAD

**Issue by tylerclark** [nuxt-modules/ionic#221]
### 📚 What are you trying to do?

I tried to run:
```
npm init nuxt-app test
cd test
npm install @nuxtjs/ionic -D
```

I do not get a `nuxt.config.ts` file, but instead a `nuxt.config.js` file. When I add `'@nuxtjs/ionic'` to `modules` array I get:

```
> nuxt


 FATAL  Cannot read property 'optimizeDeps' of undefined                        00:46:35

  at setup (node_modules/@nuxtjs/ionic/dist/module.mjs:157:56)
  at ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │   ✖ Nuxt Fatal Error                                            │
   │                                                                 │
   │   TypeError: Cannot read property 'optimizeDeps' of undefined   │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

```

### 🔍 What have you tried?

I tried to also run `npx create-nuxt-app test` but results were the same

### ℹ️ Additional context

Perhaps it's me. What else should I do to spin up a nuxt + ionic project?

UPDATE: When I ran `npx nuxi init test` I think I got a working project!

**Comment by danielroe** [comment]
Yes - sorry about that! The `npm init nuxt-app` command will run the Nuxt 2 CLI for starting a new project - and this library only supports Nuxt 3.

Glad to hear things are starting to work. There is one bug I'm cutting a release for shortly (once I merge https://github.com/nuxt-modules/ionic/pull/223).

**Comment by tylerclark** [comment]
Ahhhh, I had no idea since I never worked on Nuxt before v3! Thanks for that revelation!!!
