### ISSUE TITLE
fix: useIonRouter() cannot be used in middleware

### ISSUE THREAD

**Issue by larrasu** [nuxt-modules/ionic#234]
### 🐛 The bug

I tried using `useIonRouter()` for the forward animation, but it doesn't work. Shows an error instead:
```
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot destructure property 'canGoBack' of 'inject(...)' as it is undefined.
```

### 🛠️ To reproduce

https://stackblitz.com/edit/github-c5k7xk?file=composables%2FuseUser.ts,pages%2Ftabs%2Ftab1.vue,pages%2Ftabs%2Ftab3.vue,middleware%2Fauth.ts

### 🌈 Expected behaviour

Clicking login button in Tab 1 should navigate to Tab 3. Clicking on Tab 3 doesn't work too.

**Comment by folamy** [comment]
I'm having this issue too

**Comment by jfbloom22** [comment]
This might not be an Ionic specific issue.  Nuxt suggest avoiding using the router inside middleware and doing this:

Nuxt2
```
export default function ({ store, redirect }) {
  // If the user is not authenticated
  if (!store.state.authenticated) {
    return redirect('/login')
  }
}

```

Nuxt3
```
export default defineNuxtRouteMiddleware((to, from) => {
  const auth = useState('auth')
  if (!auth.value.authenticated) {
    return navigateTo('/login')
  }
})

```

**Comment by danielroe** [comment]
You can also directly return the route you want to navigate to, e.g.  `return '/login'`
