### ISSUE TITLE
help: Best way for tabs? No pages/index.vue do not generate index.html upon build.

### ISSUE THREAD

**Issue by larrasu** [nuxt-modules/ionic#237]
### 📚 What are you trying to do?

I tried following the [playground](https://stackblitz.com/github/nuxt-modules/ionic/tree/main/playground)'s way to have tabs. But after running `npx nuxi generate` or `npx nuxi build`, it doesn't generate an `index.html` file so I cannot run `npx cap sync` since it needs the `index.html`.

EDIT: Based on the [docs](https://ionic.nuxtjs.org/features#page-routing), it's not advised to use `NuxtLayout`. I tried using layouts but it does really mess up the routing.

### 🔍 What have you tried?

The only workaround is to have `pages/index.vue` as an onboarding page. But not all apps need that.

**Comment by BenWaNH** [comment]
For me, i set ssr to false in nuxt.config and i run nuxt generate and cap sync. It seems to work

**Comment by danielroe** [comment]
you can add the routes to generate in `nitro.prerender.routes`, or add `alias: ['/']` to one of your pages.

**Comment by aaronksaunders** [comment]
here is a sample repo based on the playground project with ionic capacitor added and configured to deploy to an IOS device, I just added an alias for the index to tabs.vue and did the necessary changes for ionic.config.json

Please take a look and add them to the project if there are issues.

https://github.com/aaronksaunders/ionic-nuxt-capacitor-playground

**Comment by reslear** [comment]
or this worked 
<img width="206" alt="Screenshot 2023-04-14 at 15 22 52" src="https://user-images.githubusercontent.com/12596485/232055597-981ed6a0-265a-4788-aac6-821e0d0f7b94.png">

then `index/home.vue` add: 

```ts
definePageMeta({
  alias: ['/'],
})
```
