### ISSUE TITLE
feat: Supporting Hot Reload

### ISSUE THREAD

**Issue by adhamfarrag** [nuxt-modules/ionic#24]
### 🆒 Your use case

Very interesting project @danielroe and the team. Thank you all.

I tried supporting hot reload to a nuxt/ionic project. Here's what I did:

1. Installing `@ionic/cli` as a dependency. 
2. adding `"ionic:serve": "nuxt dev"` command in package.json.

That's it. It worked for me. 

It's worth mentioning that when I tried to run the iOS Simulator, I saw this error message from Ionic VSCode Extension.

![Screen Shot 2022-07-12 at 1 10 56 AM](https://user-images.githubusercontent.com/23562275/178322319-eb0d976e-a67d-4bac-8d7c-e88a8a5baf00.png)

### 🆕 The solution you'd like

Supporting Hot Reload in a way that Ionic VSCode understands.

**Comment by Tragio** [comment]
If for some reason the Ionic VSC Plugin doesn't like your `package.json`, make sure you have a name and a version.

```json
  "name": "app",
  "version": "0.10.0",
 ```

**Comment by danielroe** [comment]
@Tragio Maybe worth adding to docs? Or printing a warning message when Nuxt starts if missing?
