### ISSUE TITLE
fix: Status code 200 is returning for not-found pages.

### ISSUE THREAD

**Issue by ozum** [nuxt-modules/ionic#275]
### 🐛 The bug

Hi,

Pages that cannot be found return `200 OK` instead of `404`. This problem only happens if I add `nuxt/ionic` to the project.

Please see the screenshot below. (Below on the right-hand side, you can see the status code is 200)

![image](https://user-images.githubusercontent.com/1497060/223980273-7adbe530-a10d-49cb-8767-2766c96baf8d.png)

### 🛠️ To reproduce

https://stackblitz.com/edit/github-u1b9sb?file=pages/tabs.vue

### 🌈 Expected behaviour

Status code of 404.

### ℹ️ Additional context

To reproduce it:

1. Open playground. (I didn't change a single bit from default one)
2. Navigate to a non existing page. (i.e. `/x`)

**Comment by aaronksaunders** [comment]
Why don’t you create an actual project that e can run to reproduce the issue? What you have provided is not very helpful in getting an answer for you.

**Comment by ozum** [comment]
Hi, @aaronksaunders. Thanks for the answer.

> Why don’t you create an actual project that e can run to reproduce the issue? What you have provided is not very helpful in getting an answer for you.

I was just starting a project and have only one test page and a single server api route, so the default playground example is nearly the same as my actual project.

Nonetheless, I added the page and api too. Please see `tabs.vue` page in the the updated playground link.

**Comment by danielroe** [comment]
This is happening because `@nuxtjs/ionic` sets `ssr: false`. In this case, because there is no rendering of the Vue app on the server, there is no way to know whether there should be a 404 response (that is, whether the router has a match).
