### ISSUE TITLE
fix: Navigating between menu entries fails after the second click with an error message

### ISSUE THREAD

**Issue by robotex82** [nuxt-modules/ionic#285]
### 🐛 The bug

Navigating between menu entries fails after the second click with an error message.
.
Steps to reproduce:

1. Go to https://bowlforfun-frontend-staging.netlify.app/
2. Open the Main Menu by clicking on the hamburger icon in the navigation bar
3. Click on "About"
4. See that the current page is the "About" page ("/about")
5. Again, open the main menu by clicking on the hamburger icon in the navigation bar
6. Click on "Home"
7. See that the application does not navigation to "Home"
8. In the Javascript Console output you can see following error message:

```
[@ionic/vue Warning]: The view you are trying to render for path / does not have the required <ion-page> component. Transitions and lifecycle methods may not work as expected.

See https://ionicframework.com/docs/vue/navigation#ionpage for more information.
...
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classList')
...
```

GitHub Repo: https://github.com/robotex82/bowforfun-frontend
Public URL: https://bowlforfun-frontend-staging.netlify.app/

### 🛠️ To reproduce

https://stackblitz.com/github/robotex82/bowforfun-frontend/tree/feature/BFF-0-ionic-setup

Here is a video of the current behaviour: 

https://user-images.githubusercontent.com/655932/225315626-5357db7b-7b42-4d73-a0c0-a5c691d1af48.mp4

### 🌈 Expected behaviour

* Navigating between navigation items should be possible an unlimited amount of times
* There should be no error message in the console when clicking navigation items

### ℹ️ Additional context

* I can observe the same behaviour on my local machine running `npm run dev`
* I have not been able to work around the error, i.e. by trying:
  * Different combinations of having the ion-page element on different places
  * Placing the ion-pabe element in a layout, in the app.vue file on different levels of nesting

I used the documentation on:
  * https://ionic.nuxtjs.org/features
  * https://ionicframework.com/docs/vue/your-first-app
  * https://ionicframework.com/docs/api/menu

And the youtube video here: https://www.youtube.com/watch?v=f4sB7NhCgRw

**Comment by Tragio** [comment]
Hi @robotex82 👋 

Your repo doesn't have Ionic installed, is just Nuxt3 barebone.

**Comment by Adashi12** [comment]
I have a similar issue, when I navigate to a page the first time it works. But if I click on a link to a page I already have been to, it changes the url, but does not navigate.

I tried all the documented ways for navigating from the docs: https://ionicframework.com/docs/vue/navigation
The only way it works is a full page refresh, which of course is not desirable.

I'm getting this error:

Uncaught (in promise) TypeError: enteringEl is undefined
    NuxtJS
        isViewVisible
        handlePageTransition
        setupViewItem
        setup
        callWithErrorHandling
        callWithAsyncErrorHandling
        job
        callWithErrorHandling
        flushJobs

**Comment by simondib** [comment]
> [@ionic/vue Warning]: The view you are trying to render for path / does not have the required <ion-page> component. Transitions and lifecycle methods may not work as expected.

You will see this error if your page doesn't include the <ion-page> wrapper.

**Comment by simondib** [comment]
> [@ionic/vue Warning]: The view you are trying to render for path / does not have the required <ion-page> component. Transitions and lifecycle methods may not work as expected.
> 
> See https://ionicframework.com/docs/vue/navigation#ionpage for more information.
> ...
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classList')
> ...

You will see this error if your page doesn't include the <ion-page> wrapper.

**Comment by Adashi12** [comment]
Yes, it was my bad.
I had the <ion-page> wrapper, but it was not the root element.
It works as expected now.
