### ISSUE TITLE
fix: TypeError: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by devzakir** [nuxt-modules/ionic#312]
### 🐛 The bug

Gives an error while navigating on certain pages, sometime it gives an error sometimes not. odd behavier. 
On my mac, I am getting this error sometimes, but My team members are getting this error very often. 

Detailed Loom
https://www.loom.com/share/dfcf5e59aa2b4d578d71fb6ca20873e0

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pathname')
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/33604077/229424440-0574f446-1ce1-46e2-81e7-f51d4f09c251.png">

**Steps to Reproduce**
1. Run the project 
2. Go to Browse Jobs and then Job Details
3. Reload the page few times or go back to homepage and try to visit again. 

**Ionic Info**
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/index.js
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.20.9 (/Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.6.2

Capacitor:

   Capacitor CLI      : 4.7.1
   @capacitor/android : 4.7.1
   @capacitor/core    : 4.7.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.19.0 (/Users/devzakir/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 8.19.3
   OS     : macOS Unknown

### 🛠️ To reproduce

https://github.com/devzakir/ionic-nuxt-mobile-app

### 🌈 Expected behaviour

Smoth Routing Experience across all OS

**Comment by Tragio** [comment]
Hi @devzakir 👋 

That is because you are using in the `app.vue` the following:

```html
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
```

"Nuxt utilities like definePageMeta will continue to work, but you should avoid using <NuxtPage> or <NuxtLayout>."

**Comment by devzakir** [comment]
@Tragio Thanks for the reply. But are you telling me to stop using Nuxt Layout?

**Comment by danielroe** [comment]
See https://ionic.nuxtjs.org/features#customizing-your-root-appvue.

**Comment by devzakir** [comment]
Thanks @danielroe , Getting the same error but this time it works without breaking the app. 

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/33604077/231126506-f607daa3-92cc-4e44-82ba-0fe13531a26e.png">
