### ISSUE TITLE
help: Do you support Nuxt 2?

### ISSUE THREAD

**Issue by badihi** [nuxt-modules/ionic#333]
### 📚 What are you trying to do?

I'm trying to get this module to work on Nuxt 2.

### 🔍 What have you tried?

The getting started guide seems to be not usable on Nuxt 2, or at least I'm doing it wrong.
Please tell me what to do.

### ℹ️ Additional context

Migrating projects from Nuxt 2 to Nuxt 3 takes time and it is so nice to be able to use ionic on Nuxt 2 as well since the migration is in progress.

**Comment by danielroe** [comment]
This module does not work in Nuxt 2.
