### ISSUE TITLE
`dist` folder should not be a symlink

### ISSUE THREAD

**Issue by MadDog4533** [nuxt-modules/ionic#363]
### 📚 What are you trying to do?

Is this compatible with nuxt 3.5?
Advertised as out of the box, no config needed module, but the way Nuxt 3.5 generates files, config needs to be changed or switched to SPA.
`Nuxi generate` creates a symbolic link to .output/public that ionic sync does not like.

Anyway, cheers for the project!

**Comment by danielroe** [comment]
For this purpose, we should be able to copy the generated files into a newly created `dist` folder.
