### ISSUE TITLE
fix: the 0.12.0 version is not available on npm

### ISSUE THREAD

**Issue by oumarbarry** [nuxt-modules/ionic#395]
### 🐛 The bug

Currently on NPM, the latest version is 0.11.0

<img width="1398" alt="Screen Shot 2023-06-26 at 10 30 06" src="https://github.com/nuxt-modules/ionic/assets/83463097/a27601b6-6830-41f4-8646-e6e4313d7e8c">

### 🛠️ To reproduce

N/A

### 🌈 Expected behaviour

Free 0.12.0 dear @danielroe  😆

**Comment by danielroe** [comment]
😆 0.12.1 is now flying free!

https://media.giphy.com/media/gw3W39Rt2z0yl4ju/giphy.gif
