### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ekayembe** [nuxt-modules/ionic#406]

**Comment by danielroe** [comment]
See https://github.com/nuxt-modules/ionic/issues/217#issuecomment-1399287584

**Comment by ekayembe** [comment]
@danielroe following instructions on #217 makes the layout appear but without the content of the slot. So it inverses the issue.

**Comment by geraldmaale** [comment]
> 

@danielroe To make the slot work by following #217, update to the following:
`<ion-router-outlet />` where ever you've used `<slot />`. 
It worked for me.
