### ISSUE TITLE
help: degenerator security issue

### ISSUE THREAD

**Issue by xXAinzXx** [nuxt-modules/ionic#422]
### 📚 What are you trying to do?

One of the dependencies 'degenerator' relies on vm2, and apparently a vulnerability has been found, see:
https://github.com/advisories/GHSA-g644-9gfx-q4q4

So my question is, can nuxt/ionic still be used in production or should it be removed from important projects for the time beeing?
I am still inexperienced in this field so excuse my question.

### 🔍 What have you tried?

A patch isn't available, the author said vm2 will be discontinued:
https://github.com/patriksimek/vm2

### ℹ️ Additional context

npm audit log:
  degenerator  >=3.0.0
  Depends on vulnerable versions of vm2

**Comment by GreenmeisterDavid** [comment]
Also looking for a fix for this, NPM warns about it when installing. However, I since this package is dependent on @ionic/cli (which in turn also has this vulnerability), I think they should address this issue.

**Comment by danielroe** [comment]
Agreed. :+1:
