### ISSUE TITLE
feat: useIonRouter() is missing isReady() from vue-router?

### ISSUE THREAD

**Issue by chrisspiegl** [nuxt-modules/ionic#465]
### 🆒 Your use case

Waiting for the page / router to be ready when loading a page.

### 🆕 The solution you'd like

`vue-router` via `useRouter()` in Nuxt supports `await useRouter().isReady()` which is super useful to wait for a page to finish loading.

I expected `useIonRouter()` to also have this but appears it does not.

Maybe this can be implemented, or is there an alternative I should use?

Thank you 🌸,
Chris

### 🔍 Alternatives you've considered

Using `useRouter().isReady()` inside my Nuxt/Ionic app appears to be working as expected. But I thought it would be cleaner to have only `useIonRouter` in the project instead of mixing it.

**Comment by CHIBX** [comment]
@chrisspiegl The Ionic team mentioned the use of vue-router's **`useRouter()`** working well.
That has the method you are looking for

**Comment by danielroe** [comment]
I think you should use both composables - when required.
