### ISSUE TITLE
fix: Modal System not working

### ISSUE THREAD

**Issue by evanlegamer** [nuxt-modules/ionic#474]
### 🐛 The bug

Modals not working in @nuxt/ionic, whatever ion-modal technic you want to use, the ion-backdrop always display with a greater z-index as your modal or your modal content never display.

On my current project, the ion-backdrop display with a greater z-index and so I cannot see my modal.

I tried a fresh project to see what happen with only nuxt/ionic and got the same problem

![Vidéo sans titre ‐ Réalisée avec Clipchamp (1)](https://github.com/nuxt-modules/ionic/assets/18480367/e2247bb7-0208-4b8e-85cb-4695cf0f76ca)

On this one, reproduced also on stackblitz, the content of the modal is not even displayed and we have an empty ion-page instead.

### 🛠️ To reproduce

https://stackblitz.com/edit/github-zenff6?file=pages%2Findex.vue

### 🌈 Expected behaviour

Display the modal content and the ion-backdrop behind with a smaller z-index than the modal.

### ℹ️ Additional context

Tried to reinstall multiple times the project and relaunch the server multiple times, and once on 15, it has worked normally.
I don't understand why.

**Comment by Adashi12** [comment]
You didn't wrap your modal in `<ion-modal>`, I'm not sure if this is the only problem.

I always implement it with the `:is-open` method and it works fine:
https://ionicframework.com/docs/api/modal#using-isopen

Also you can ditch all those imports, that's why we use Nuxt :)

**Comment by huckbee** [comment]
I am now also having this issue.
It was working fine last week with the `modalController.create` method. But today, the black backdrop took over.  I tried the `:is-open` method, but I am getting the same behavior.

**Comment by Adashi12** [comment]
This is really weird.
After upgrading to the latest version (0.15, I was on 0.12.1), I also had problems with modals and toasts.

By adding the plugin as @huckbee suggested it worked again. Though to my understanding, this should not be necessary, or am I missing something?

**Comment by danielroe** [comment]
If you are still experiencing this, would you open a new issue with a reproduction? 🙏
