### ISSUE TITLE
fix: when built and previewed, error 500 due to undefined beforeResolve pops up

### ISSUE THREAD

**Issue by Hibryda** [nuxt-modules/ionic#484]
### 🐛 The bug

Versions:

- @nuxtjs/ionic: 0.12.1
- nuxt: 3.8.1,

Only `app.vue` and `pages/index.vue` present, containing the simplest arrangement as the following:

- `app.vue`
```vue
<template>
  <ion-app>
    <ion-router-outlet />
  </ion-app>
</template>
```
- `index.vue`
```vue
<template>
  <ion-page>
    <ion-content>
        Dummy text
    </ion-content>
  </ion-page>
</template>
```

Nuxt config:
```typescript
export default defineNuxtConfig({
  // devtools: { enabled: true },
  modules: ["@nuxtjs/ionic"],
  ssr: false
})
```

When built and previewed, the following error is reported:
`[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'beforeResolve')`

### 🛠️ To reproduce

https://stackblitz.com/edit/github-kscu4y

### 🌈 Expected behaviour

No error

### ℹ️ Additional context

Switching off router integration resolves the issue, meaning that here lies the problem.

The issue is present only when the app is built, in the development mode everything works fine.

**Comment by Adashi12** [comment]
I upgraded Nuxt from 3.6.5 to 3.8.1 and also had issues. After reverting back it works again.
You could try with a lower Nuxt version.

Also the `preview` script often does not work properly (giving me 404 and other errors). 
I use `npx http-server dist` instead after `nuxi generate`.

**Comment by vlacour97** [comment]
I have the same issue, can anyone suggest a fix?

**Comment by frankspee** [comment]
I also ran into this issue last week. Took me to much hours to see this breaking bug. Happy to see there is a workaround for now! That works great. Thanks @markglattback for that.

I guess this is now a problem for everyone using this module with Nuxt `3.7.4` or higher. The workaround looks experimental, so might stop working in the future.

Can this be fixed easily in this module? Or is it actually a bug in Nuxt? Do we know?

Side-note: now seeing this open for almost 2 months I guess this is not a really active developed module. Shame on the Ionic website they fail to mention the WIP/not active maintained status of this module. Makes me thinks about not using the module. It does not seem really stable for production use. I do want to help, just never done module development before.

**Comment by frankspee** [comment]
> I have the same issue, can anyone suggest a fix?

Check the posts above you for the fix/workaround for now.

**Comment by frankspee** [comment]
Just to make people not run around checking issues, this issue is related: https://github.com/nuxt-modules/ionic/issues/460

**Comment by vlacour97** [comment]
I would like to use payload extraction to have a static SPA with data pre-loaded in SSG
