### ISSUE TITLE
help: Nuxt auto-import doesn't display ionic component types

### ISSUE THREAD

**Issue by KiddoV** [nuxt-modules/ionic#496]
### 📚 What are you trying to do?

The auto-import component should point to an ionic type right?

![type](https://github.com/nuxt-modules/ionic/assets/28552977/4510c549-a5e0-418b-8c51-c73b8df6de98)

But VSCode only assume it is a ``any`` type.

### ℹ️ Additional context

```vue
//index.vue
<script setup lang="ts">
definePageMeta({
    alias: ["/", "/overview"],
})
</script>

<template>
    <ion-page translucent>
        <ion-toolbar>
            <ion-title>Overview</ion-title>
        </ion-toolbar>
    </ion-page>
</template>
```

```json
//tsconfig.json
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "baseUrl": "",
    "types": []
  },
}
```

**Comment by danielroe** [comment]
You might need to explicitly install `@ionic/vue` or set `shamefully-hoist=true` in your `.npmrc` file.

**Comment by berial** [comment]
use `npm install @ionic/vue -D`
