### ISSUE TITLE
Failed to resolve component: ion-picker-column & ion-picker-column-option

### ISSUE THREAD

**Issue by YuriiDunaev** [nuxt-modules/ionic#559]
### 🐛 The bug

When adding the "ion-picker-column" component:
`<ion-picker>
        <ion-picker-column :value="active">
          <ion-picker-column-option
            :value="item"
            v-for="item in items"
            :key="item"
            >{{ item }}</ion-picker-column-option
          >
        </ion-picker-column>
      </ion-picker>`

I'm getting this errors:
`[Vue warn]: Failed to resolve component: ion-picker-column
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. `

`[Vue warn]: Failed to resolve component: ion-picker-column-option
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.`

### 🛠️ To reproduce

https://stackblitz.com/edit/github-zh2v4k?file=pages%2Ftabs.vue

### 🌈 Expected behaviour

These components are expected to be found

**Comment by danielroe** [comment]
This should be resolved in the next release.

Let me know if not and I'll reopen.
