### ISSUE TITLE
docs: How can i emulate on Android emulator from Webstorm/PhpStorm

### ISSUE THREAD

**Issue by BenWaNH** [nuxt-modules/ionic#56]
### 📚 Is your documentation request related to a problem?

I'm using PhpStorm in Windows 10 to work on my project. I installed Android Studio too.

On web browser 3000 port it works fine, but, device api are not available in browser, i need to really emulate on device.

I tried to add an "External tool"
![image](https://user-images.githubusercontent.com/3426306/188648561-686d4258-993f-46e3-8f89-074628a37fcc.png)
It runs, but nothing happens on emulator
![image](https://user-images.githubusercontent.com/3426306/188648623-1c74366e-3209-4d37-b1c6-522872c4430a.png)
I'm missing something?! Is it possible? If yes, how? Which steps to follow...

Thanks

### 🔍 Where should you find it?

New section How emulate ?

**Comment by aaronksaunders** [comment]
how are you deploying to the emulator?

**Comment by BenWaNH** [comment]
Hi @aaronksaunders . This is my question yes
I would like to test my app on emulator, not on my web browser. Have you any clue?

**Comment by SuperSchek** [comment]
> Hi @aaronksaunders . This is my question yes I would like to test my app on emulator, not on my web browser. Have you any clue?

Check the Ionic/Capacitor docs. It has detailed instructions on how to do this.
