### ISSUE TITLE
release of 0.14

### ISSUE THREAD

**Issue by oumarbarry** [nuxt-modules/ionic#561]
### 🆒 Your use case

Using Ionic 8

### 🆕 The solution you'd like

New release

### ℹ️ Additional info

I'm curious if there are any outstanding issues that need to be addressed before.

For instance, I've noticed that Ionic has introduced a new method for managing dark mode.
We could potentially incorporate support for dark and high-contrast themes through configuration in the future, or we may choose to leave this task to be performed manually.

**Comment by danielroe** [comment]
The last feature I have in mind is the merge of https://github.com/nuxt-modules/ionic/pull/518.
