### ISSUE TITLE
Can't install nuxt/ionic@0.14.0

### ISSUE THREAD

**Issue by Andr9651** [nuxt-modules/ionic#565]
### 🐛 The bug

Trying to install nuxt/ionic@0.14.0 in a new nuxt project results in the following error: `'husky' is not recognized as an internal or external command,`

### Reproduction Steps:
1. `npx nuxi@latest init <project name>`
2. select npm
4. `npx nuxi@latest module add ionic` or `npm i @nuxtjs/ionic`

### Things I've tried:
* `npm i @nuxtjs/ionic@0.13.1` works without issue.
* Installing Husky first seems fix the issue.
* Running the commands on 3 different windows machines and a mac all with the same result.
* Running the commands in CodeSandbox which gives the same result.
* Running the commands in Stackblitz which oddly enough succeeds. Can't figure out why though...

### Windows:
![image](https://github.com/nuxt-modules/ionic/assets/40522728/0e6ff862-d7d9-4984-bbfe-09d368fa82c9)

### Mac:
![image](https://github.com/nuxt-modules/ionic/assets/40522728/b6dab594-22c7-4b5b-bd3e-01506f9c4077)

### Codesandbox:
![image](https://github.com/nuxt-modules/ionic/assets/40522728/e8c90c96-8cdc-47e6-a610-10ccccdcbdef)

### 🛠️ To reproduce

Unsure what to put here?

### 🌈 Expected behaviour

Installing succeeds with requiring Husky.

**Comment by jsayer101** [comment]
Got the same problem while trying to install the package using `npx nuxi@latest module add ionic` and yarn.
Also seems to be a husky issue (`command not found: husky`).

**Comment by keduardo2117** [comment]
I tried updating from 0.13 and I'm getting a similar error, the post-install script fails.
