### ISSUE TITLE
Custom theme variables not working - 14.0.0

### ISSUE THREAD

**Issue by silvercent011** [nuxt-modules/ionic#568]
### 🐛 The bug

The module doesn't recognizes custom theme variables on css files, downgrading to v0.13.1 works.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-qx18gq?file=nuxt.config.ts

### 🌈 Expected behaviour

Expects the module recognizes and apply ionic variables overwritten in css files.

**Comment by danielroe** [comment]
We should investigate whether this is an upstream issue with Ionic, as this module has never done anything with the CSS variables, just documented how to set them.

**Comment by silvercent011** [comment]
Updating, apparently with Vue/Vite it continues to work, looking at module code now...

https://stackblitz.com/edit/github-gxs7ou-myj5vx?file=src%2Ftheme%2Fvariables.css

**Comment by danielroe** [comment]
Thank you ❤️
