### ISSUE TITLE
Runtime error: Failed to resolve import "#vue-router"

### ISSUE THREAD

**Issue by Rizzato95** [nuxt-modules/ionic#580]
### 🐛 The bug

In an empty Nuxt project if I simply add @nuxt/ionic (from v.0.14.0), I get this runtime error:

`Internal server error: Failed to resolve import "#vue-router" from "node_modules/@nuxtjs/ionic/dist/runtime/composables/head.mjs?v=7856ef51". Does the file exist?`

The module works as expected with v.0.13.x

### 🛠️ To reproduce

https://codesandbox.io/p/devbox/nuxt-ionic-vh6nqz

### 🌈 Expected behaviour

The application should start as always

**Comment by danielroe** [comment]
This should be resolved in v0.15+.
