### ISSUE TITLE
Problems that had to explicitly import useRoute

### ISSUE THREAD

**Issue by binochoi** [nuxt-modules/ionic#581]
### 📚 Is your documentation request related to a problem?

I was able to change useRoute through unimport. It will take a lot of testing, but I think it would be better to add it to documentation.

### 🔍 Where should you find it?

```ts
// nuxt.config.ts
{
  imports: {
    imports: [
      {
        name: 'useRoute',
        from: 'vue-router'
      }
    ]
  },
}
```
u might confront type error or 503 problem, shoud to override unimport
```json
// package.json
{
  "pnpm": {
    "overrides": {
      "unimport": "latest"
    }
  },
}
```

### ℹ️ Additional context

hopefully my situation help this plugin

**Comment by Nisgrak** [comment]
@binochoi Hi! You recomend this change or the testing was unsuccessfull?

**Comment by binochoi** [comment]
@Nisgrak i couldnt avoid type absension and error of `Duplicated imports "useRoute", the one from "#app/composables/router" has been ignored and "vue-router" is used`.

now but im using this solution instead
```ts
// nuxt.config.ts
import Unimport from 'unimport/unplugin'
{
  vite: {
    plugins: [
      Unimport.vite({
        dts: true,
        imports: [
          {
            name: 'useRoute',
            from: 'vue-router',
          },
        ]
      })
    ]
  }
}
```

and then add `unimport.d.ts` file to `include` of `tsconfig.json`.

This is only a temporary measure and works well, but for problems where the useIonRouter is seen as any type, '@ionic/vue' must be imported directly, and the type cannot be overwritten due to the nature of the typecript, so the problem caused by overlapping autoImport does not seem to be solved.

It's not a perfect solution, as you have to hack the nuxt and redefine the auto import.
