### ISSUE TITLE
fix: getActivePinia was called with no active Pinia within global middleware

### ISSUE THREAD

**Issue by whynotea** [nuxt-modules/ionic#60]
### 🐛 The bug

Thanks for the recent middleware support.
Unfortunately when using pinia within middleware files with the .global suffix the following error is being raised:
[Vue Router warn]: Unexpected error when starting the router: Error: [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?
	const pinia = createPinia()
	app.use(pinia)
This will fail in production.

This does not occur in middleware without the .global suffix. So I can workaround this by defining which middleware to use on every page.
The issue doesn't occur in a nuxt project without nuxt-ionic.

### 🛠️ To reproduce

https://stackblitz.com/edit/github-ezppn4?file=package.json

### 🌈 Expected behaviour

Pinia is called successfully similar to calls to non-global middleware.

### ℹ️ Additional context

An example of a nuxt global middleware without nuxt-ionic which does work:
https://stackblitz.com/edit/github-me1qn4?file=package.json

**Comment by fristyr** [comment]
same here

**Comment by chrisspiegl** [comment]
I just ran into something that feels similar.

In Nuxt (and in named individually assigned middlewares) the App context is fully existent.

But for some reason, with nuxt-ionic, the first time the page is opened (without SSR in my case), the middleware is ran waaaaay early in the stack before any App Setup or anything.

The result is that things like vuefire usually work in middlewares (and they do on the calls when changing routes) but not on the first page load.

I have not yet found a way to make this work besides having to put the `definePageMeta` into every page I want the middleware to run on. But it's a middleware that is supposed to run on pretty much all my pages 🙈.

**Comment by chrisspiegl** [comment]
I think I found a "workaround":

- You register a plugin
- In the plugin you do two things:
- 1) you register your middleware to run on `router.beforeEach`
- 2) you run the middleware as well.

This achieves both: the middleware runs on first load AND it runs on each route navigation after that.

Please note: I have not tested this with SSR, or PWA or any other fancy things. Just worked in my environment and it seems to be the solution for me at this time.

Here is my code sample of such a plugin:

```js
export default defineNuxtPlugin(async (nuxtApp) => {
  console.log('👨‍💻 Loading auth login check plugin')

  const router = useRouter()
  router.beforeEach(checkLoginState)
  await checkLoginState(useRoute(), undefined)

  async function checkLoginState(to: any, from: any) {
      console.log('🛠️ Authentication running on initial & following navigations')
  }
})
```

**Comment by chrisspiegl** [comment]
A possibly even cleaner solution is probably the use of `addRouteMiddleware`.

The reason would be that this uses the Nuxt function `addRouteMiddleware` which is one step further out and will then also be used by the Ionic Router if I get my things correctly.

This way it's registered in both frameworks and not just in the ionic router.

Another important note I found:

Navigation via `navigateTo` does not seem to work in this implementation. I had to use the `useRouter().push({ name: 'login' }` way of doing things. But that seems to work fine.

Code snippet:

```js
export default defineNuxtPlugin(async (nuxtApp) => {
  console.log('👨‍💻 Loading auth login check plugin - this should only show up once in the console')

  addRouteMiddleware('global-auth-check', checkLoginState, { global: true })
  await checkLoginState(useRoute(), undefined)

  async function checkLoginState(to: any, from: any) {
      console.log('🛠️ Authentication running on initial & following navigations - this should show up every time you navigate (including the first load)')
  }
})
```

**Comment by danielroe** [comment]
This is not reproducible with the latest version of this module + pinia.
