### ISSUE TITLE
Confused By What You Mean By Setup For Capacitor?

### ISSUE THREAD

**Issue by aaronksaunders** [nuxt-modules/ionic#7]
### 📚 Is your documentation request related to a problem?

The documentation states that it is ready to go with capacitor, but capacitor is not installed? It was confusing to me and might be confusing to others.

Also I think there is "Capacitor" to run a PWA and "Capacitor" to install on a device which again can be confusing to the reader. I had to to a bit more configure to get the capacitor working and get a sample project installed in my emulator and device.

I was not surprised because I have gone down this road before, but as I stated above, it might not be clear to the average user.

**Comment by danielroe** [comment]
Hopefully now resolved in 3f3e2473aabe4af96f325e4e3ae39b50535fa81e. Let me know if you're looking for more info. I also plan to build out a tighter integration later, with auto-syncing + HMR.
